# Overrides values from docker-compose.yml for local development.

services:
  api:
    volumes:
      - ../StockTracker.API/app:/home/appuser/src/app:ro
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      LOG_JSON: "false"
      LOG_SQL: "true"
    command: >
      uvicorn app.main:app
        --host 0.0.0.0
        --port 8000
        --reload
        --reload-dir /home/appuser/src/app

  datacollector:
    volumes:
      - ../StockTracker.DataCollector/app:/home/appuser/src/app:ro
    environment:
      LOG_JSON: "false"
    command: >
      uvicorn app.main:app
        --host 0.0.0.0
        --port 8001
        --reload
        --reload-dir /home/appuser/src/app

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
